#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o tmp/main ./cmd/server"
  bin     = "./tmp/main"
  delay = 1000
  pre_cmd = ["make swag"]
  exclude_dir = ["docs", "tmp", "infra"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "2s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
