services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    container_name: penster-app-local
    command: ["air", "-c", "air.toml"]
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_PORT=8080
      - AUTO_MIGRATE=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=penster
      - DB_PASSWORD=placeholder
      - DB_NAME=penster
      - DB_SSLMODE=disable
      - OTEL_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - penster-local
    volumes:
      - ..:/app

  postgres:
    image: postgres:16-alpine
    container_name: penster-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=penster
      - POSTGRES_PASSWORD=placeholder
      - POSTGRES_DB=penster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penster -d penster"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - penster-local


volumes:
  postgres_data:

networks:
  penster-local:
    driver: bridge
