services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    container_name: penster-app-local
    command: ["air", "-c", "air.toml"]
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_PORT=8080
      - AUTO_MIGRATE=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=penster
      - DB_PASSWORD=placeholder
      - DB_NAME=penster
      - DB_SSLMODE=disable
      - OTEL_ENABLED=true
      - TEMPO_ENDPOINT=tempo:4317
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - penster-local
    volumes:
      - ..:/app

  postgres:
    image: postgres:16-alpine
    container_name: penster-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=penster
      - POSTGRES_PASSWORD=placeholder
      - POSTGRES_DB=penster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penster -d penster"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - penster-local

  loki:
    container_name: grafana-loki
    image: grafana/loki:3.6.10
    restart: unless-stopped
    ports:
      - "13100:3100"
    volumes:
      - loki_data:/data
      - ./loki.yaml:/etc/loki/local-config.yaml
    networks:
      - penster-local
    command: -config.expand-env=true -config.file=/etc/loki/local-config.yaml

  tempo:
    container_name: grafana-tempo
    image: grafana/tempo:2.6.1
    restart: unless-stopped
    ports:
      - "13200:3200"
      - "13217:4317"
      - "13218:4318"
    volumes:
      - tempo_data:/var/tempo
      - ./tempo.yaml:/etc/tempo.yaml
    networks:
      - penster-local
    command: -config.file=/etc/tempo.yaml

  mimir:
    container_name: grafana-mimir
    image: grafana/mimir:2.17.9
    restart: unless-stopped
    ports:
      - "13080:8080"
    environment:
      - MIMIR_HTTP_PORT=8080
      - MIMIR_GRPC_PORT=9095
      - MIMIR_STORAGE_BACKEND=filesystem
      - MIMIR_STORAGE_FILESYSTEM_DIRECTORY=/data
    volumes:
      - mimir_data:/data
    networks:
      - penster-local

  grafana:
    container_name: grafana-grafana
    image: grafana/grafana:12.3.0
    restart: unless-stopped
    ports:
      - "13300:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    networks:
      - penster-local
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
      - tempo
      - mimir

volumes:
  postgres_data:
  grafana_data:
  tempo_data:
  loki_data:
  mimir_data:

networks:
  penster-local:
    driver: bridge