// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (sub_id, name, type, balance)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, sub_id, name, type, balance, deleted_at, created_at, updated_at
`

type CreateAccountParams struct {
	Name    string
	Type    string
	Balance int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Name, arg.Type, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
UPDATE accounts
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sub_id, name, type, balance, deleted_at, created_at, updated_at
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, deleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, sub_id, name, type, balance, deleted_at, created_at, updated_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountBySubID = `-- name: GetAccountBySubID :one
SELECT id, sub_id, name, type, balance, deleted_at, created_at, updated_at
FROM accounts
WHERE sub_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountBySubID(ctx context.Context, subID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountBySubID, subID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
WITH base_query AS (
    SELECT id, sub_id, name, type, balance, deleted_at, created_at, updated_at
    FROM accounts
    WHERE deleted_at IS NULL
),
search_query AS (
    SELECT id, sub_id, name, type, balance, deleted_at, created_at, updated_at FROM base_query
    WHERE
        ($1::uuid IS NULL OR sub_id = $1)
        AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
),
count_query AS (
    SELECT count(*) as total FROM search_query
),
paginated_query AS (
    SELECT
        id, sub_id, name, type, balance, deleted_at, created_at, updated_at
    FROM search_query
    WHERE
        ($3::text = 'name' AND (
            ($4::text = 'asc' AND name > $5) OR
            ($4::text = 'desc' AND name < $5) OR
            ($4::text = 'asc' AND $5 IS NULL) OR
            ($4::text = 'desc' AND $5 IS NULL)
        ))
        OR ($3::text = 'created_at' AND (
            ($4::text = 'asc' AND created_at > $6) OR
            ($4::text = 'desc' AND created_at < $6) OR
            ($4::text = 'asc' AND $6 IS NULL) OR
            ($4::text = 'desc' AND $6 IS NULL)
        ))
        OR ($3::text = 'updated_at' AND (
            ($4::text = 'asc' AND updated_at > $7) OR
            ($4::text = 'desc' AND updated_at < $7) OR
            ($4::text = 'asc' AND $7 IS NULL) OR
            ($4::text = 'desc' AND $7 IS NULL)
        ))
        OR ($3::text = 'balance' AND (
            ($4::text = 'asc' AND balance > $8) OR
            ($4::text = 'desc' AND balance < $8) OR
            ($4::text = 'asc' AND $8 IS NULL) OR
            ($4::text = 'desc' AND $8 IS NULL)
        ))
        OR $3::text = ''
    ORDER BY
        CASE WHEN $3::text = 'name' AND $4::text = 'asc' THEN name END ASC,
        CASE WHEN $3::text = 'name' AND $4::text = 'desc' THEN name END DESC,
        CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at END ASC,
        CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at END DESC,
        CASE WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN updated_at END ASC,
        CASE WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN updated_at END DESC,
        CASE WHEN $3::text = 'balance' AND $4::text = 'asc' THEN balance END ASC,
        CASE WHEN $3::text = 'balance' AND $4::text = 'desc' THEN balance END DESC,
        CASE WHEN $3::text = '' THEN id END ASC
    LIMIT NULLIF($9, 0)
)
SELECT
    pq.id, pq.sub_id, pq.name, pq.type, pq.balance, pq.deleted_at, pq.created_at, pq.updated_at,
    cq.total
FROM paginated_query pq, count_query cq
`

type ListAccountsParams struct {
	SubID           pgtype.UUID
	Q               string
	SortBy          string
	SortOrder       string
	CursorName      string
	CursorCreatedAt pgtype.Timestamptz
	CursorUpdatedAt pgtype.Timestamptz
	CursorBalance   int64
	PageSize        interface{}
}

type ListAccountsRow struct {
	ID        int32
	SubID     pgtype.UUID
	Name      string
	Type      string
	Balance   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Total     int64
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.SubID,
		arg.Q,
		arg.SortBy,
		arg.SortOrder,
		arg.CursorName,
		arg.CursorCreatedAt,
		arg.CursorUpdatedAt,
		arg.CursorBalance,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = COALESCE($1, name),
    type = COALESCE($2, type),
    balance = COALESCE($3, balance),
    updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, sub_id, name, type, balance, deleted_at, created_at, updated_at
`

type UpdateAccountParams struct {
	Name    string
	Type    string
	Balance int64
	ID      int32
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, sub_id, name, type, balance, deleted_at, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	Balance int64
	ID      int32
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.Balance, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
