// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (sub_id, name, type)
VALUES (gen_random_uuid(), $1, $2)
RETURNING id, sub_id, name, type, deleted_at, created_at, updated_at
`

type CreateCategoryParams struct {
	Name string
	Type string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
UPDATE categories
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sub_id, name, type, deleted_at, created_at, updated_at
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, sub_id, name, type, deleted_at, created_at, updated_at
FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySubID = `-- name: GetCategoryBySubID :one
SELECT id, sub_id, name, type, deleted_at, created_at, updated_at
FROM categories
WHERE sub_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySubID(ctx context.Context, subID pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySubID, subID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    c.id, c.sub_id, c.name, c.type, c.deleted_at, c.created_at, c.updated_at,
    cnt.total
FROM categories c
CROSS JOIN (SELECT count(*) as total FROM categories c2
    WHERE c2.deleted_at IS NULL
    AND ($1::uuid IS NULL OR c2.sub_id = $1::uuid)
    AND ($2::text IS NULL OR c2.name ILIKE '%' || $2::text || '%')
) cnt
WHERE c.deleted_at IS NULL
    AND ($1::uuid IS NULL OR c.sub_id = $1::uuid)
    AND ($2::text IS NULL OR c.name ILIKE '%' || $2::text || '%')
    AND (
        ($3::text = 'name' AND (
            ($4::text = 'asc' AND c.name > $5::text) OR
            ($4::text = 'desc' AND c.name < $5::text) OR
            ($4::text = 'asc' AND $5::text IS NULL) OR
            ($4::text = 'desc' AND $5::text IS NULL)
        ))
        OR ($3::text = 'created_at' AND (
            ($4::text = 'asc' AND c.created_at > $6::timestamptz) OR
            ($4::text = 'desc' AND c.created_at < $6::timestamptz) OR
            ($4::text = 'asc' AND $6::timestamptz IS NULL) OR
            ($4::text = 'desc' AND $6::timestamptz IS NULL)
        ))
        OR ($3::text = 'updated_at' AND (
            ($4::text = 'asc' AND c.updated_at > $7::timestamptz) OR
            ($4::text = 'desc' AND c.updated_at < $7::timestamptz) OR
            ($4::text = 'asc' AND $7::timestamptz IS NULL) OR
            ($4::text = 'desc' AND $7::timestamptz IS NULL)
        ))
        OR $3::text = ''
    )
ORDER BY
    CASE WHEN $3::text = 'name' AND $4::text = 'asc' THEN c.name END ASC,
    CASE WHEN $3::text = 'name' AND $4::text = 'desc' THEN c.name END DESC,
    CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN c.created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN c.created_at END DESC,
    CASE WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN c.updated_at END ASC,
    CASE WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN c.updated_at END DESC,
    CASE WHEN $3::text = '' THEN c.id END ASC
LIMIT NULLIF($8, 0)
`

type ListCategoriesParams struct {
	Column1 pgtype.UUID
	Column2 string
	Column3 string
	Column4 string
	Column5 string
	Column6 pgtype.Timestamptz
	Column7 pgtype.Timestamptz
	Column8 interface{}
}

type ListCategoriesRow struct {
	ID        int32
	SubID     pgtype.UUID
	Name      string
	Type      string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Total     int64
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.Name,
			&i.Type,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE(NULLIF($1, ''), name),
    type = COALESCE(NULLIF($2, ''), type),
    updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, sub_id, name, type, deleted_at, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name interface{}
	Type interface{}
	ID   int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Type, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.Name,
		&i.Type,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
