// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraft = `-- name: CreateDraft :one
INSERT INTO drafts (account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, source, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type CreateDraftParams struct {
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      pgtype.Numeric
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
	Source            string
	Status            string
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.TransactedAt,
		arg.Notes,
		arg.Source,
		arg.Status,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getDraftByID = `-- name: GetDraftByID :one
SELECT
    d.id, d.sub_id, d.account_id, d.transfer_account_id, d.category_id,
    d.transaction_type, d.title, d.base_amount, d.enhanced_amount,
    d.currency, d.currency_rate, d.transacted_at, d.notes,
    d.source, d.status, d.confirmed_at, d.rejected_at,
    d.deleted_at, d.created_at, d.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id
FROM drafts d
LEFT JOIN accounts a ON d.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON d.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON d.category_id = c.id AND c.deleted_at IS NULL
WHERE d.id = $1 AND d.deleted_at IS NULL
`

type GetDraftByIDRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	Source               string
	Status               string
	ConfirmedAt          pgtype.Timestamptz
	RejectedAt           pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
}

func (q *Queries) GetDraftByID(ctx context.Context, id int32) (GetDraftByIDRow, error) {
	row := q.db.QueryRow(ctx, getDraftByID, id)
	var i GetDraftByIDRow
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.Source,
		&i.Status,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountSubID,
		&i.TransferAccountSubID,
		&i.CategorySubID,
	)
	return i, err
}

const getDraftBySubID = `-- name: GetDraftBySubID :one
SELECT
    d.id, d.sub_id, d.account_id, d.transfer_account_id, d.category_id,
    d.transaction_type, d.title, d.base_amount, d.enhanced_amount,
    d.currency, d.currency_rate, d.transacted_at, d.notes,
    d.source, d.status, d.confirmed_at, d.rejected_at,
    d.deleted_at, d.created_at, d.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id
FROM drafts d
LEFT JOIN accounts a ON d.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON d.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON d.category_id = c.id AND c.deleted_at IS NULL
WHERE d.sub_id = $1 AND d.deleted_at IS NULL
`

type GetDraftBySubIDRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	Source               string
	Status               string
	ConfirmedAt          pgtype.Timestamptz
	RejectedAt           pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
}

func (q *Queries) GetDraftBySubID(ctx context.Context, subID pgtype.UUID) (GetDraftBySubIDRow, error) {
	row := q.db.QueryRow(ctx, getDraftBySubID, subID)
	var i GetDraftBySubIDRow
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.Source,
		&i.Status,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountSubID,
		&i.TransferAccountSubID,
		&i.CategorySubID,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT
    d.id, d.sub_id, d.account_id, d.transfer_account_id, d.category_id,
    d.transaction_type, d.title, d.base_amount, d.enhanced_amount,
    d.currency, d.currency_rate, d.transacted_at, d.notes,
    d.source, d.status, d.confirmed_at, d.rejected_at,
    d.deleted_at, d.created_at, d.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id,
    cnt.total
FROM drafts d
LEFT JOIN accounts a ON d.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON d.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON d.category_id = c.id AND c.deleted_at IS NULL
CROSS JOIN (SELECT count(*) as total FROM drafts d2
    WHERE d2.deleted_at IS NULL
    AND ($1::text IS NULL OR d2.source = $1)
    AND ($2::text IS NULL OR d2.status = $2)
) cnt
WHERE d.deleted_at IS NULL
    AND ($1::text IS NULL OR d.source = $1)
    AND ($2::text IS NULL OR d.status = $2)
ORDER BY d.created_at DESC
LIMIT NULLIF($3, 0)
`

type ListDraftsParams struct {
	Column1  string
	Column2  string
	PageSize interface{}
}

type ListDraftsRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	Source               string
	Status               string
	ConfirmedAt          pgtype.Timestamptz
	RejectedAt           pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
	Total                int64
}

func (q *Queries) ListDrafts(ctx context.Context, arg ListDraftsParams) ([]ListDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDrafts, arg.Column1, arg.Column2, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsRow
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.AccountID,
			&i.TransferAccountID,
			&i.CategoryID,
			&i.TransactionType,
			&i.Title,
			&i.BaseAmount,
			&i.EnhancedAmount,
			&i.Currency,
			&i.CurrencyRate,
			&i.TransactedAt,
			&i.Notes,
			&i.Source,
			&i.Status,
			&i.ConfirmedAt,
			&i.RejectedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountSubID,
			&i.TransferAccountSubID,
			&i.CategorySubID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDraft = `-- name: SoftDeleteDraft :one
UPDATE drafts
SET deleted_at = NOW(), updated_at = NOW()
WHERE sub_id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) SoftDeleteDraft(ctx context.Context, subID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, softDeleteDraft, subID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE drafts
SET
    account_id = COALESCE(NULLIF($1, 0), account_id),
    transfer_account_id = COALESCE($2, transfer_account_id),
    category_id = COALESCE(NULLIF($3, 0), category_id),
    transaction_type = COALESCE(NULLIF($4, ''), transaction_type),
    title = COALESCE(NULLIF($5, ''), title),
    base_amount = COALESCE(NULLIF($6, 0), base_amount),
    enhanced_amount = COALESCE($7, enhanced_amount),
    currency = COALESCE(NULLIF($8, ''), currency),
    currency_rate = COALESCE($9, currency_rate),
    transacted_at = COALESCE($10, transacted_at),
    notes = COALESCE($11, notes),
    updated_at = NOW()
WHERE sub_id = $12 AND deleted_at IS NULL
RETURNING id
`

type UpdateDraftParams struct {
	AccountID         interface{}
	TransferAccountID pgtype.Int4
	CategoryID        interface{}
	TransactionType   interface{}
	Title             interface{}
	BaseAmount        interface{}
	EnhancedAmount    pgtype.Int8
	Currency          interface{}
	CurrencyRate      pgtype.Numeric
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
	SubID             pgtype.UUID
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.TransactedAt,
		arg.Notes,
		arg.SubID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateDraftStatus = `-- name: UpdateDraftStatus :one
UPDATE drafts
SET
    status = $1,
    confirmed_at = CASE WHEN $1 = 'confirmed' THEN NOW() ELSE confirmed_at END,
    rejected_at = CASE WHEN $1 = 'rejected' THEN NOW() ELSE rejected_at END,
    updated_at = NOW()
WHERE sub_id = $2 AND deleted_at IS NULL
RETURNING id
`

type UpdateDraftStatusParams struct {
	Status string
	SubID  pgtype.UUID
}

func (q *Queries) UpdateDraftStatus(ctx context.Context, arg UpdateDraftStatusParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateDraftStatus, arg.Status, arg.SubID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
