// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32
	SubID     pgtype.UUID
	Name      string
	Type      string
	Balance   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Category struct {
	ID        int32
	SubID     pgtype.UUID
	Name      string
	Type      string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Draft struct {
	ID                int32
	SubID             pgtype.UUID
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      pgtype.Numeric
	Notes             pgtype.Text
	Source            string
	Status            string
	ConfirmedAt       pgtype.Timestamptz
	RejectedAt        pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RateCurrency struct {
	ID           pgtype.UUID
	FromCurrency string
	ToCurrency   string
	Rate         pgtype.Numeric
	RateDate     pgtype.Date
	CreatedAt    pgtype.Timestamptz
}

type Transaction struct {
	ID                int32
	SubID             pgtype.UUID
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      pgtype.Numeric
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
