// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountBreakdown = `-- name: GetAccountBreakdown :many
SELECT
    a.id as account_id,
    a.name as account_name,
    t.transaction_type,
    COALESCE(SUM(t.enhanced_amount), 0) as total
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id AND a.deleted_at IS NULL
WHERE t.deleted_at IS NULL
    AND t.transacted_at >= $1
    AND t.transacted_at <= $2
GROUP BY a.id, t.transaction_type
`

type GetAccountBreakdownParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetAccountBreakdownRow struct {
	AccountID       pgtype.Int4
	AccountName     pgtype.Text
	TransactionType string
	Total           interface{}
}

func (q *Queries) GetAccountBreakdown(ctx context.Context, arg GetAccountBreakdownParams) ([]GetAccountBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getAccountBreakdown, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountBreakdownRow
	for rows.Next() {
		var i GetAccountBreakdownRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.TransactionType,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT
    c.sub_id as category_id,
    c.name as category_name,
    c.type as category_type,
    COALESCE(SUM(t.enhanced_amount), 0) as total
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id AND c.deleted_at IS NULL
WHERE t.deleted_at IS NULL
    AND t.transacted_at >= $1
    AND t.transacted_at <= $2
GROUP BY c.sub_id
`

type GetCategoryBreakdownParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetCategoryBreakdownRow struct {
	CategoryID   pgtype.UUID
	CategoryName pgtype.Text
	CategoryType pgtype.Text
	Total        interface{}
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalBalance = `-- name: GetTotalBalance :one
SELECT COALESCE(SUM(balance), 0) as total_balance
FROM accounts
WHERE deleted_at IS NULL
`

func (q *Queries) GetTotalBalance(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalBalance)
	var total_balance interface{}
	err := row.Scan(&total_balance)
	return total_balance, err
}

const getTotalsByType = `-- name: GetTotalsByType :many
SELECT
    transaction_type,
    COALESCE(SUM(enhanced_amount), 0) as total
FROM transactions
WHERE deleted_at IS NULL
    AND transacted_at >= $1
    AND transacted_at <= $2
GROUP BY transaction_type
`

type GetTotalsByTypeParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetTotalsByTypeRow struct {
	TransactionType string
	Total           interface{}
}

func (q *Queries) GetTotalsByType(ctx context.Context, arg GetTotalsByTypeParams) ([]GetTotalsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getTotalsByType, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalsByTypeRow
	for rows.Next() {
		var i GetTotalsByTypeRow
		if err := rows.Scan(&i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrends = `-- name: GetTrends :many
SELECT
    DATE(transacted_at) as date,
    transaction_type,
    COALESCE(SUM(enhanced_amount), 0) as total
FROM transactions
WHERE deleted_at IS NULL
    AND transacted_at >= $1
    AND transacted_at <= $2
GROUP BY DATE(transacted_at), transaction_type
`

type GetTrendsParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetTrendsRow struct {
	Date            pgtype.Date
	TransactionType string
	Total           interface{}
}

func (q *Queries) GetTrends(ctx context.Context, arg GetTrendsParams) ([]GetTrendsRow, error) {
	rows, err := q.db.Query(ctx, getTrends, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrendsRow
	for rows.Next() {
		var i GetTrendsRow
		if err := rows.Scan(&i.Date, &i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
