// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateTransactionParams struct {
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      pgtype.Numeric
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.TransactedAt,
		arg.Notes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteTransaction = `-- name: DeleteTransaction :one
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTransaction, id)
	err := row.Scan(&id)
	return id, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
    t.id, t.sub_id, t.account_id, t.transfer_account_id, t.category_id,
    t.transaction_type, t.title, t.base_amount, t.enhanced_amount,
    t.currency, t.currency_rate, t.transacted_at, t.notes,
    t.deleted_at, t.created_at, t.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON t.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON t.category_id = c.id AND c.deleted_at IS NULL
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTransactionByIDRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountSubID,
		&i.TransferAccountSubID,
		&i.CategorySubID,
	)
	return i, err
}

const getTransactionBySubID = `-- name: GetTransactionBySubID :one
SELECT
    t.id, t.sub_id, t.account_id, t.transfer_account_id, t.category_id,
    t.transaction_type, t.title, t.base_amount, t.enhanced_amount,
    t.currency, t.currency_rate, t.transacted_at, t.notes,
    t.deleted_at, t.created_at, t.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON t.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON t.category_id = c.id AND c.deleted_at IS NULL
WHERE t.sub_id = $1 AND t.deleted_at IS NULL
`

type GetTransactionBySubIDRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
}

func (q *Queries) GetTransactionBySubID(ctx context.Context, subID pgtype.UUID) (GetTransactionBySubIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionBySubID, subID)
	var i GetTransactionBySubIDRow
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountSubID,
		&i.TransferAccountSubID,
		&i.CategorySubID,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.sub_id, t.account_id, t.transfer_account_id, t.category_id,
    t.transaction_type, t.title, t.base_amount, t.enhanced_amount,
    t.currency, t.currency_rate, t.transacted_at, t.notes,
    t.deleted_at, t.created_at, t.updated_at,
    a.sub_id as account_sub_id,
    ta.sub_id as transfer_account_sub_id,
    c.sub_id as category_sub_id,
    cnt.total
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id AND a.deleted_at IS NULL
LEFT JOIN accounts ta ON t.transfer_account_id = ta.id AND ta.deleted_at IS NULL
LEFT JOIN categories c ON t.category_id = c.id AND c.deleted_at IS NULL
CROSS JOIN (SELECT count(*) as total FROM transactions t2
    WHERE t2.deleted_at IS NULL
    AND ($1::uuid IS NULL OR t2.sub_id = $1)
    AND ($2::int IS NULL OR t2.account_id = $2)
    AND ($3::int IS NULL OR t2.category_id = $3)
    AND ($4::text IS NULL OR t2.transaction_type = $4)
    AND ($5::text IS NULL OR t2.title ILIKE '%' || $5 || '%')
) cnt
WHERE t.deleted_at IS NULL
    AND ($1::uuid IS NULL OR t.sub_id = $1)
    AND ($2::int IS NULL OR t.account_id = $2)
    AND ($3::int IS NULL OR t.category_id = $3)
    AND ($4::text IS NULL OR t.transaction_type = $4)
    AND ($5::text IS NULL OR t.title ILIKE '%' || $5 || '%')
    AND (
        ($6::text = 'title' AND (
            ($7::text = 'asc' AND t.title > $8) OR
            ($7::text = 'desc' AND t.title < $8) OR
            ($7::text = 'asc' AND $8 IS NULL) OR
            ($7::text = 'desc' AND $8 IS NULL)
        ))
        OR ($6::text = 'transacted_at' AND (
            ($7::text = 'asc' AND t.transacted_at > $9) OR
            ($7::text = 'desc' AND t.transacted_at < $9) OR
            ($7::text = 'asc' AND $9 IS NULL) OR
            ($7::text = 'desc' AND $9 IS NULL)
        ))
        OR ($6::text = 'created_at' AND (
            ($7::text = 'asc' AND t.created_at > $10) OR
            ($7::text = 'desc' AND t.created_at < $10) OR
            ($7::text = 'asc' AND $10 IS NULL) OR
            ($7::text = 'desc' AND $10 IS NULL)
        ))
        OR ($6::text = 'amount' AND (
            ($7::text = 'asc' AND t.enhanced_amount > $11) OR
            ($7::text = 'desc' AND t.enhanced_amount < $11) OR
            ($7::text = 'asc' AND $11 IS NULL) OR
            ($7::text = 'desc' AND $11 IS NULL)
        ))
        OR $6::text = ''
    )
ORDER BY
    CASE WHEN $6::text = 'title' AND $7::text = 'asc' THEN t.title END ASC,
    CASE WHEN $6::text = 'title' AND $7::text = 'desc' THEN t.title END DESC,
    CASE WHEN $6::text = 'transacted_at' AND $7::text = 'asc' THEN t.transacted_at END ASC,
    CASE WHEN $6::text = 'transacted_at' AND $7::text = 'desc' THEN t.transacted_at END DESC,
    CASE WHEN $6::text = 'created_at' AND $7::text = 'asc' THEN t.created_at END ASC,
    CASE WHEN $6::text = 'created_at' AND $7::text = 'desc' THEN t.created_at END DESC,
    CASE WHEN $6::text = 'amount' AND $7::text = 'asc' THEN t.enhanced_amount END ASC,
    CASE WHEN $6::text = 'amount' AND $7::text = 'desc' THEN t.enhanced_amount END DESC,
    CASE WHEN $6::text = '' THEN t.id END ASC
LIMIT NULLIF($12, 0)
`

type ListTransactionsParams struct {
	Column1        pgtype.UUID
	Column2        int32
	Column3        int32
	Column4        string
	Column5        string
	Column6        string
	Column7        string
	Title          string
	TransactedAt   pgtype.Date
	CreatedAt      pgtype.Timestamptz
	EnhancedAmount pgtype.Int8
	Column12       interface{}
}

type ListTransactionsRow struct {
	ID                   int32
	SubID                pgtype.UUID
	AccountID            int32
	TransferAccountID    pgtype.Int4
	CategoryID           pgtype.Int4
	TransactionType      string
	Title                string
	BaseAmount           int64
	EnhancedAmount       pgtype.Int8
	Currency             string
	CurrencyRate         pgtype.Numeric
	TransactedAt         pgtype.Date
	Notes                pgtype.Text
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	AccountSubID         pgtype.UUID
	TransferAccountSubID pgtype.UUID
	CategorySubID        pgtype.UUID
	Total                int64
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Title,
		arg.TransactedAt,
		arg.CreatedAt,
		arg.EnhancedAmount,
		arg.Column12,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.AccountID,
			&i.TransferAccountID,
			&i.CategoryID,
			&i.TransactionType,
			&i.Title,
			&i.BaseAmount,
			&i.EnhancedAmount,
			&i.Currency,
			&i.CurrencyRate,
			&i.TransactedAt,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountSubID,
			&i.TransferAccountSubID,
			&i.CategorySubID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    account_id = COALESCE($1, account_id),
    transfer_account_id = $2,
    category_id = $3,
    transaction_type = COALESCE($4, transaction_type),
    title = COALESCE($5, title),
    base_amount = COALESCE($6, base_amount),
    enhanced_amount = $7,
    currency = COALESCE($8, currency),
    currency_rate = COALESCE($9, currency_rate),
    notes = $10,
    updated_at = NOW()
WHERE id = $11 AND deleted_at IS NULL
RETURNING id
`

type UpdateTransactionParams struct {
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      pgtype.Numeric
	Notes             pgtype.Text
	ID                int32
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.Notes,
		arg.ID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
