// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID                 int32
	SubID              pgtype.UUID
	AccountID          int32
	TransferAccountID  pgtype.Int4
	CategoryID         pgtype.Int4
	TransactionType    string
	Title              string
	BaseAmount         int64
	EnhancedAmount     pgtype.Int8
	Currency           string
	CurrencyRate       float64
	TransactedAt       pgtype.Date
	Notes              pgtype.Text
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
`

type CreateTransactionParams struct {
	AccountID         int32
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   string
	Title             string
	BaseAmount        int64
	EnhancedAmount    pgtype.Int8
	Currency          string
	CurrencyRate      float64
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.TransactedAt,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :one
UPDATE transactions
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, deleteTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
FROM transactions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionBySubID = `-- name: GetTransactionBySubID :one
SELECT id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
FROM transactions
WHERE sub_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionBySubID(ctx context.Context, subID pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionBySubID, subID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
WITH base_query AS (
    SELECT id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
    FROM transactions
    WHERE deleted_at IS NULL
),
search_query AS (
    SELECT id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at FROM base_query
    WHERE
        ($1::uuid IS NULL OR sub_id = $1)
        AND ($2::int IS NULL OR account_id = $2)
        AND ($3::int IS NULL OR category_id = $3)
        AND ($4::text IS NULL OR transaction_type = $4)
        AND ($5::text IS NULL OR title ILIKE '%' || $5 || '%')
),
count_query AS (
    SELECT count(*) as total FROM search_query
),
paginated_query AS (
    SELECT
        id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
    FROM search_query
    WHERE
        ($6::text = 'title' AND (
            ($7::text = 'asc' AND title > $8) OR
            ($7::text = 'desc' AND title < $8) OR
            ($7::text = 'asc' AND $8 IS NULL) OR
            ($7::text = 'desc' AND $8 IS NULL)
        ))
        OR ($6::text = 'transacted_at' AND (
            ($7::text = 'asc' AND transacted_at > $9) OR
            ($7::text = 'desc' AND transacted_at < $9) OR
            ($7::text = 'asc' AND $9 IS NULL) OR
            ($7::text = 'desc' AND $9 IS NULL)
        ))
        OR ($6::text = 'created_at' AND (
            ($7::text = 'asc' AND created_at > $10) OR
            ($7::text = 'desc' AND created_at < $10) OR
            ($7::text = 'asc' AND $10 IS NULL) OR
            ($7::text = 'desc' AND $10 IS NULL)
        ))
        OR ($6::text = 'amount' AND (
            ($7::text = 'asc' AND enhanced_amount > $11) OR
            ($7::text = 'desc' AND enhanced_amount < $11) OR
            ($7::text = 'asc' AND $11 IS NULL) OR
            ($7::text = 'desc' AND $11 IS NULL)
        ))
        OR $4::text = ''
    ORDER BY
        CASE WHEN $4::text = 'title' AND $5::text = 'asc' THEN title END ASC,
        CASE WHEN $4::text = 'title' AND $5::text = 'desc' THEN title END DESC,
        CASE WHEN $4::text = 'transacted_at' AND $5::text = 'asc' THEN transacted_at END ASC,
        CASE WHEN $4::text = 'transacted_at' AND $5::text = 'desc' THEN transacted_at END DESC,
        CASE WHEN $4::text = 'created_at' AND $5::text = 'asc' THEN created_at END ASC,
        CASE WHEN $4::text = 'created_at' AND $5::text = 'desc' THEN created_at END DESC,
        CASE WHEN $4::text = 'amount' AND $5::text = 'asc' THEN enhanced_amount END ASC,
        CASE WHEN $4::text = 'amount' AND $5::text = 'desc' THEN enhanced_amount END DESC,
        CASE WHEN $4::text = '' THEN id END ASC
    LIMIT NULLIF($10, 0)
)
SELECT
    pq.id, pq.sub_id, pq.account_id, pq.transfer_account_id, pq.category_id, pq.transaction_type, pq.title, pq.base_amount, pq.enhanced_amount, pq.currency, pq.currency_rate, pq.transacted_at, pq.notes, pq.deleted_at, pq.created_at, pq.updated_at,
    cq.total
FROM paginated_query pq, count_query cq
`

type ListTransactionsParams struct {
	SubID               pgtype.UUID
	AccountID           pgtype.Int4
	CategoryID          pgtype.Int4
	TransactionType     string
	Q                   string
	SortBy              string
	SortOrder           string
	CursorTitle         string
	CursorTransactedAt  pgtype.Date
	CursorCreatedAt     pgtype.Timestamptz
	CursorEnhancedAmount int64
	PageSize            interface{}
}

type ListTransactionsRow struct {
	ID                 int32
	SubID              pgtype.UUID
	AccountID          int32
	TransferAccountID  pgtype.Int4
	CategoryID         pgtype.Int4
	TransactionType    string
	Title              string
	BaseAmount         int64
	EnhancedAmount     pgtype.Int8
	Currency           string
	CurrencyRate       float64
	TransactedAt       pgtype.Date
	Notes              pgtype.Text
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Total              int64
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.SubID,
		arg.AccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Q,
		arg.SortBy,
		arg.SortOrder,
		arg.CursorTitle,
		arg.CursorTransactedAt,
		arg.CursorCreatedAt,
		arg.CursorEnhancedAmount,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.AccountID,
			&i.TransferAccountID,
			&i.CategoryID,
			&i.TransactionType,
			&i.Title,
			&i.BaseAmount,
			&i.EnhancedAmount,
			&i.Currency,
			&i.CurrencyRate,
			&i.TransactedAt,
			&i.Notes,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    account_id = COALESCE($1, account_id),
    transfer_account_id = $2,
    category_id = $3,
    transaction_type = COALESCE($4, transaction_type),
    title = COALESCE($5, title),
    base_amount = COALESCE($6, base_amount),
    enhanced_amount = $7,
    currency = COALESCE($8, currency),
    currency_rate = COALESCE($9, currency_rate),
    transacted_at = COALESCE($10, transacted_at),
    notes = $11,
    updated_at = NOW()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, sub_id, account_id, transfer_account_id, category_id, transaction_type, title, base_amount, enhanced_amount, currency, currency_rate, transacted_at, notes, deleted_at, created_at, updated_at
`

type UpdateTransactionParams struct {
	AccountID         pgtype.Int4
	TransferAccountID pgtype.Int4
	CategoryID        pgtype.Int4
	TransactionType   pgtype.Text
	Title             pgtype.Text
	BaseAmount        pgtype.Int8
	EnhancedAmount    pgtype.Int8
	Currency          pgtype.Text
	CurrencyRate      float64
	TransactedAt      pgtype.Date
	Notes             pgtype.Text
	ID                int32
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.AccountID,
		arg.TransferAccountID,
		arg.CategoryID,
		arg.TransactionType,
		arg.Title,
		arg.BaseAmount,
		arg.EnhancedAmount,
		arg.Currency,
		arg.CurrencyRate,
		arg.TransactedAt,
		arg.Notes,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SubID,
		&i.AccountID,
		&i.TransferAccountID,
		&i.CategoryID,
		&i.TransactionType,
		&i.Title,
		&i.BaseAmount,
		&i.EnhancedAmount,
		&i.Currency,
		&i.CurrencyRate,
		&i.TransactedAt,
		&i.Notes,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
