apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://grafana-loki:3100
    uid: loki
    isDefault: false
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://grafana-tempo:3200
    uid: tempo
    isDefault: true
    editable: false

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://grafana-mimir:9009
    uid: mimir
    isDefault: false
    editable: false